name: Publish Chrome Extension
on:
  push:
    branches:
      - main

  jobs:
    build-and-publish:
      # https://developer.chrome.com/docs/webstore/using-api
      # Challenges:
        # Chrome Extensions go through a review so all changes to npm package need to be backward compatable because we can publish npm before the extension is approved and we don't know when the extension will be approved
        