name: Publish NPM Package

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.7.0'
          registry-url: 'https://registry.npmjs.org/'

      - name: Move to package directory
        run: cd package
      - name: Install Dependencies
        run: npm install

      # If your package needs to be built (e.g., TypeScript to JavaScript), include this step
      - name: Build
        run: npm run build

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
